### ISSUE TITLE
ERROR event: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by abhithakre** [elstudio/actions-settings#6]
Hi @elstudio 
  I am getting error while executing Github action.
Below are the details:-

09:50:40.471Z ERROR event: Cannot read property 'includes' of undefined (id=1b149410-1f9e-4c46-96f6-f1d524ac182a)
  TypeError: Cannot read property 'includes' of undefined
      at payload.commits.find.commit (/app/node_modules/probot-settings/index.js:11:27)
      at Array.find (<anonymous>)
      at robot.on (/app/node_modules/probot-settings/index.js:10:46)
  --
  event: {
    "event": "push",
    "id": "1b149410-1f9e-4c46-96f6-f1d524ac182a",
    "repository": "abhithakre/repo-name"
  }

https://github.com/abhithakre/repo-name/runs/1090457022?check_suite_focus=true

**Comment by abhithakre** [comment]
done

**Comment by stocky37** [comment]
@abhithakre what was the problem? I had the same issue.

**Comment by nirnanaaa** [comment]
we're also running into the same issue, @abhithakre would you mind sharing your solution with us?

**Comment by flugg** [comment]
@abhithakre I'm stuck on the same error. If you remember how you fixed this, please share with us
